### PR TITLE
Admin listening sessions, closes #86

### LINKED ISSUE #86: convert  admin listening_sessions/index

### PR DESCRIPTION
**Pull request by AnnaCW**
This PR converts most of one view (admin/listening_sessions/index.html.erb) to React. 

I still need to format the date/times in the "Date Updated" and "Date Created" columns of the table. This was previously handled with helper methods in the listening sessions model. Opened issue #93.

### CODE REVIEW

**Comment by dalexj** [comment]
be sure to get semicolons in here. the rest looks good

**Comment by AnnaCW** [comment]
Thanks @dalexj. I added the ones I believe were missing in this PR after a bit of research. JSHint does not seem to be working with jsx files. If you have a good source on this, I'd be interested.

**Comment by dalexj** [comment]
I've seen eslint used most of the time for jsx files, or I think there's a jsxhint instead you could try

**Comment by AnnaCW** [comment]
Thanks @dalexj, I will check those out.

**Pull request merged**
